[variables]
NODE_VERSION = "20.18.0"
NIXPACKS_NODE_PACKAGE_MANAGER = "pnpm"

[phases.install]
cmd = "pnpm install --frozen-lockfile"

[phases.build]
cmd = "pnpm run build"

[start]
cmd = "pnpm start"

[build]
env = ["NODE_ENV=production"]